### ISSUE TITLE
Send reminders to customers for appointments

### ISSUE THREAD

**Issue by T-Syme** [McGill-ECSE321-Winter2021/project-group-09#103]
Implement a way to send reminders to customers for all of their appointments

TODOs:
- [x] Create reminders when an appointment is created OR right after it starts (up to you, just note that if it is done on create, then the reminder should change if the appointment is cancelled)
- [x] Set the reminder types (one reminder for service, another for appointment confirmation)
- [x] Set the corresponding date (an arbitrary future date for the service reminder, and immediately for the confirmation)
- [x] Find a way to trigger the sending of the reminders booked for future dates (could be automated call once a day to check through all existing reminders)
- [x] Send the reminder to the customer's email

**Comment by sandyl289** [comment]
**Note to myself:**
**Plan:**
![image](https://user-images.githubusercontent.com/70775435/110896805-51a98180-82ca-11eb-97b6-54d0eb82035b.png)

**Comment by sandyl289** [comment]
**Modified plan:** 

![image](https://user-images.githubusercontent.com/70775435/111002297-2fa81180-8353-11eb-8698-e0087546d75d.png)
