### ISSUE TITLE
Update UML Diagram in Wiki to match Umple Online Version

### ISSUE THREAD

**Issue by zhannaklimanova** [McGill-ECSE321-Winter2021/project-group-09#105]
There was a couple of things modified in the class diagram, the main change is the association between technician and appointment + vacations changed to holiday in association between business and timeslot.

**Comment by sandyl289** [comment]
- [ ] Add 2 more attributes for Reminder (appointmentDateTime) 
- [ ] Change enum of ReminderType (`upcomingAppointment` & `serviceReminder`)
![image](https://user-images.githubusercontent.com/70775435/110999405-50219d00-834e-11eb-9b05-927b6635129f.png)
TODO: Update Domain Model on the [Domain Model](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Domain-Model) page to be similar to the [umple diagram](https://cruise.umple.org/umpleonline/umple.php?model=21020317ygmsb729lf9)
- [ ]  Change the **vacations** to **holidays**
- [ ] Update the associations between Technician, Appointment and TimeSlot

**Comment by T-Syme** [comment]
I added the Umple version of the domain model to the wiki
