### ISSUE TITLE
RESTful Service Tests on Postman 🧪 wiki page

### ISSUE THREAD

**Issue by sandyl289** [McGill-ECSE321-Winter2021/project-group-09#149]
[Service Tests on Postman 🧪 wiki page](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/RESTful-Service-Tests-on-Postman-%F0%9F%A7%AA)

- [x] Add all screenshots into the wiki
- [x] Authentication Controller
- [x] Admin Controller
- [x] Technician Controller
- [x] Business Controller
- [x] Service Controller
- [x] Customer Controller
- [x] Appointment Controller
- [x] TimeSlot Controller
- [x] Add hyperlinks to each section

**Comment by sandyl289** [comment]
AUTHENTICATION CONTROLLER
 ✔️  Login (Admin)
![image](https://user-images.githubusercontent.com/70775435/111650731-f56bc380-87db-11eb-8ad5-5d754bb2f652.png)

**Comment by T-Syme** [comment]
✔️  Logout (Admin)

![image](https://user-images.githubusercontent.com/70815823/111650950-31068d80-87dc-11eb-9a18-9f6f9f5b56d2.png)

**Comment by T-Syme** [comment]
✔️  Login (Customer)
![image](https://user-images.githubusercontent.com/70815823/111651186-60b59580-87dc-11eb-8485-c5f5f143aaea.png)

**Comment by T-Syme** [comment]
✔️  Logout (Customer)
![image](https://user-images.githubusercontent.com/70815823/111651287-76c35600-87dc-11eb-8801-205c5951efaa.png)

**Comment by T-Syme** [comment]
✔️ Login (Technician)
![image](https://user-images.githubusercontent.com/70815823/111651333-82af1800-87dc-11eb-99bf-b7f6f0f3f589.png)

**Comment by T-Syme** [comment]
✔️ Logout (Technician)
![image](https://user-images.githubusercontent.com/70815823/111651393-8e024380-87dc-11eb-87c4-a288ab17f07f.png)

**Comment by T-Syme** [comment]
### ADMIN CONTROLLER

**Comment by T-Syme** [comment]
✔️  Register new Admin (with valid admin token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111651673-d15cb200-87dc-11eb-8286-cfdaf472b5d5.png)

 ✔️  Get Admin by Email (with valid admin token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111651836-f6512500-87dc-11eb-92b8-154b4d6c38de.png)

 ✔️  Get all admins (with valid admin token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111651889-01a45080-87dd-11eb-841c-fb4ab8b1fd54.png)

✔️  Delete admin by email (with valid admin token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111651921-08cb5e80-87dd-11eb-9e3c-210c3acf86e7.png)

**Comment by T-Syme** [comment]
### TIMESLOT CONTROLLER

✔️ Create a time slot
![image](https://user-images.githubusercontent.com/70815823/111652098-2b5d7780-87dd-11eb-9d57-7162f3aa7252.png)

✔️ Get a time slot by ID
![image](https://user-images.githubusercontent.com/70815823/111652121-31ebef00-87dd-11eb-90f1-3546d8c98486.png)

✔️Get all time slots
![image](https://user-images.githubusercontent.com/70815823/111652144-37e1d000-87dd-11eb-9329-200cb1822d92.png)

**Comment by T-Syme** [comment]
### TECHNICIAN CONTROLLER

✔️ Register New Technician (With valid admin token header from login)
![image](https://user-images.githubusercontent.com/70815823/111652461-75def400-87dd-11eb-9d2c-8b16eeb5e8be.png)

✔️ Delete a Technician (with valid admin token from login as header)
![image](https://user-images.githubusercontent.com/70815823/111652489-7b3c3e80-87dd-11eb-9608-d0f57fe14a4b.png)

✔️ Get a Technician (With valid admin token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111652529-81cab600-87dd-11eb-9df2-a248aff8bbed.png)

✔️ Get All Technicians (With valid admin token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111652550-87c09700-87dd-11eb-8e1a-20d5980f9b95.png)

✔️ See Work Hours (With valid admin  OR technician token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111652591-9018d200-87dd-11eb-8b0e-ee9ae54cb251.png)

✔️ Add Work Hours (With valid admin  OR technician token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111652621-960eb300-87dd-11eb-95dc-71657bf07e84.png)

✔️ View Appointments (With valid admin  OR technician token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111652650-9f981b00-87dd-11eb-8a41-c025bc3cbcd5.png)

✔️ View Schedule (With valid admin  OR technician token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111652676-a6bf2900-87dd-11eb-95b2-425e1870cb61.png)

✔️ Delete Specific Work Hours (With valid admin token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111652705-acb50a00-87dd-11eb-99a3-e61d039e1c4c.png)

✔️ Delete entire schedule of a technician
![image](https://user-images.githubusercontent.com/70815823/111652739-b3dc1800-87dd-11eb-96aa-db2dcd844dba.png)

✔️ Change password of technician (With valid technician token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111652771-bb032600-87dd-11eb-89da-3d6e2fdc3ef1.png)

**Comment by T-Syme** [comment]
### BUSINESS CONTROLLER

✔️ Get number of repair spots
![image](https://user-images.githubusercontent.com/70815823/111652921-d837f480-87dd-11eb-8677-980d35ca96d2.png)

✔️  Create Business (with valid admin token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111652975-e259f300-87dd-11eb-855a-52e69e3e8149.png)

✔️  Update Business (with valid admin token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111652994-e84fd400-87dd-11eb-9038-1495ef5d4a83.png)

✔️  Get Business Info 
![image](https://user-images.githubusercontent.com/70815823/111653012-edad1e80-87dd-11eb-8519-1bea6e46f446.png)

 ✔️  Get all holidays
![image](https://user-images.githubusercontent.com/70815823/111653040-f3a2ff80-87dd-11eb-8e8f-3afae36cc109.png)

 ✔️  Create new holiday (with valid admin token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111653078-fe5d9480-87dd-11eb-84c8-98dad6ee4e18.png)

 ✔️  Delete Holiday (with valid admin token from login in headers)
![image](https://user-images.githubusercontent.com/70815823/111653111-0584a280-87de-11eb-88ed-ea3ad5a81395.png)

**Comment by T-Syme** [comment]
### SERVICE CONTROLLER

✔️ Add Service (with valid Admin token from login in header)
![image](https://user-images.githubusercontent.com/70815823/111653217-1df4bd00-87de-11eb-9967-05a3635191d4.png)

✔️ Get Service by Name 
![image](https://user-images.githubusercontent.com/70815823/111653236-23520780-87de-11eb-85e5-364cbc5aae92.png)

✔️ Get All Services 
![image](https://user-images.githubusercontent.com/70815823/111653451-4f6d8880-87de-11eb-82a9-729bd1d5f9e1.png)

**Comment by T-Syme** [comment]
### CUSTOMER CONTROLLER

✔️  Create a Customer Account (Register)
![image](https://user-images.githubusercontent.com/70815823/111653588-6b712a00-87de-11eb-8df5-8a6437bf23aa.png)

✔️ Change Password (by the Customer)  
![image](https://user-images.githubusercontent.com/70815823/111653640-72983800-87de-11eb-8837-b8e0af6fd409.png)

✔️ Get a customer account by email (with valid Admin token from login in header)  
![image](https://user-images.githubusercontent.com/70815823/111653679-7926af80-87de-11eb-902f-2877fc04f283.png)

✔️ Get all existing customers (with valid Admin token from login in header)  
![image](https://user-images.githubusercontent.com/70815823/111653723-7fb52700-87de-11eb-81a1-953315e830ba.png)

✔️ View all appointments of a customer (with valid Admin token from login in header)  
![image](https://user-images.githubusercontent.com/70815823/111653802-8e9bd980-87de-11eb-86ad-cde9a65acae9.png)

✔️ View all appointments of a customer (with valid Customer token from login in header) 
![image](https://user-images.githubusercontent.com/70815823/111653852-99566e80-87de-11eb-8293-e933a76cc158.png)

✔️ Delete customer account (with valid Customer token from login in header) 
![image](https://user-images.githubusercontent.com/70815823/111653883-a07d7c80-87de-11eb-9340-feeaeca5edfe.png)

**Comment by T-Syme** [comment]
### APPOINTMENT CONTROLLER

_Currently incomplete..._

**Comment by sandyl289** [comment]
add service
![image](https://user-images.githubusercontent.com/70775435/111708661-a4c88a80-881c-11eb-8c9f-071e8226fcce.png)

**Comment by sandyl289** [comment]
![image](https://user-images.githubusercontent.com/70775435/111708921-1ef90f00-881d-11eb-8024-9ede05f3a8ba.png)
![image](https://user-images.githubusercontent.com/70775435/111709018-44861880-881d-11eb-8ce8-b44d006759b6.png)
Get all services:
![image](https://user-images.githubusercontent.com/70775435/111709229-9f1f7480-881d-11eb-9f8d-2d745dcc3d1e.png)

**Comment by sandyl289** [comment]
![image](https://user-images.githubusercontent.com/70775435/111709971-0be73e80-881f-11eb-823d-9b872f0c1727.png)

**Comment by sandyl289** [comment]
![image](https://user-images.githubusercontent.com/70775435/111710091-55378e00-881f-11eb-9541-68a6603b5dbc.png)

**Comment by sandyl289** [comment]
![image](https://user-images.githubusercontent.com/70775435/111710180-8a43e080-881f-11eb-90cd-ef14c3e0b28a.png)

**Comment by sandyl289** [comment]
![image](https://user-images.githubusercontent.com/70775435/111711027-4520ae00-8821-11eb-8639-78b233085724.png)

**Comment by sandyl289** [comment]
![image](https://user-images.githubusercontent.com/70775435/111715570-7d78ba00-882a-11eb-906a-2f076cf41cf5.png)
![image](https://user-images.githubusercontent.com/70775435/111715712-cdf01780-882a-11eb-8b70-81b10be1f710.png)

**Comment by sandyl289** [comment]
![image](https://user-images.githubusercontent.com/70775435/111717530-94211000-882e-11eb-967f-7856eb757073.png)
![image](https://user-images.githubusercontent.com/70775435/111717556-a26f2c00-882e-11eb-96a0-507c7d2960a9.png)

**Comment by sandyl289** [comment]
view customer's appt
![image](https://user-images.githubusercontent.com/70775435/111717776-1f020a80-882f-11eb-94f2-3e379a613010.png)
![image](https://user-images.githubusercontent.com/70775435/111717859-4e187c00-882f-11eb-93ad-2edfc776bcd2.png)
![image](https://user-images.githubusercontent.com/70775435/111717900-5cff2e80-882f-11eb-87bc-1ffe7e97feb7.png)

**Comment by sandyl289** [comment]
View appointments of a technician 
![image](https://user-images.githubusercontent.com/70775435/111718801-00047800-8831-11eb-8e8d-1059cf0e103c.png)
![image](https://user-images.githubusercontent.com/70775435/111718849-11e61b00-8831-11eb-8c8a-1e7fcc32393d.png)
![image](https://user-images.githubusercontent.com/70775435/111718868-1dd1dd00-8831-11eb-93b5-d3ba8f04c8c8.png)

**Comment by sandyl289** [comment]
Cancel appt:
![image](https://user-images.githubusercontent.com/70775435/111719194-c3854c00-8831-11eb-848a-764d8ae0b055.png)

**Comment by sandyl289** [comment]
Done! https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/RESTful-Service-Tests-on-Postman-%F0%9F%A7%AA
