### ISSUE TITLE
Sign Up/Register page (Admin, Customer)

### ISSUE THREAD

**Issue by sandyl289** [McGill-ECSE321-Winter2021/project-group-09#157]
### **🏁 Setup**
- [x] **Assign** yourself to this issue 

### **✅ To do:**

- [x] Read [Detailed Use Case: Register](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Detailed-Use-Cases#use-case-register)
- [x] **Draw** page mockup using [Whimsical](https://whimsical.com/repairshop-6v7GHoRVFfSSvyvUdeHaQ8) 
(After clicking on the link, you must sign in with your Google Account)

**Frontend**
- [x] Text fields for `email`, `password`, `name`, `address`, `phone number`
- [x] Add drop down menu or radio button to select user type (Admin, & Customer)
- [x] Implement frontend

### **🆘 If need help for the issue you’re working on:**

**1) Write** comments in this issue 
**2) Add** label ![image](https://user-images.githubusercontent.com/70775435/112154839-0b51fd80-8bbb-11eb-82ae-9f47dab449b0.png)
**3) Copy** the issue link and **paste** it to Discord's `#🐛issues` channel
**4)** When solved, **strike** the message in `#🐛issues`, **mark it** as `(SOLVED)`  + **remove** label `help wanted` + **write** comments in this issue 

### *Whenever something is done write a comment below.*

**Comment by sandyl289** [comment]
- Mockup done!

**When we first launch the app, we would see the login and sign up tabs.**
![image](https://user-images.githubusercontent.com/70775435/112195766-b32df200-8be0-11eb-9de4-e4bad420f6e2.png)

### I think this issue can be done together with Home Page #156  & Login #162

**Comment by JDziewonski98** [comment]
todo: improve styling, add token for register admin request, figure out how to persist the login state across page refresh
