### ISSUE TITLE
Create New Employee Account Along With a Schedule (Admin)

### ISSUE THREAD

**Issue by sandyl289** [McGill-ECSE321-Winter2021/project-group-09#158]
### **🏁 Setup**
- [ ] **Assign** yourself to this issue 

### **✅ To do:**

- [ ] Read [Detailed Use Case: Create New Employee Account Along With a Schedule](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Detailed-Use-Cases#use-case-create-new-employee-account-along-with-a-schedule)
- [ ] **Draw** page mockup using [Whimsical](https://whimsical.com/repairshop-6v7GHoRVFfSSvyvUdeHaQ8) 
(After clicking on the link, you must sign in with your Google Account)
![image](https://user-images.githubusercontent.com/70775435/112150794-df347d80-8bb6-11eb-84d8-93a33a150db0.png)

**Frontend**
- [ ] Text fields for `email`, `password`, `name`, `address`, `phone number`
- [ ] Add drop down menu or radio button to select user type (Admin or Technician)?
- [ ] Add work hours
- [ ]  Implement frontend

### **🆘 If need help for the issue you’re working on:**

**1) Write** comments in this issue 
**2) Add** label ![image](https://user-images.githubusercontent.com/70775435/112154839-0b51fd80-8bbb-11eb-82ae-9f47dab449b0.png)
**3) Copy** the issue link and **paste** it to Discord's `#🐛issues` channel
**4)** When solved, **strike** the message in `#🐛issues`, **mark it** as `(SOLVED)`  + **remove** label `help wanted` + **write** comments in this issue 

### *Whenever something is done write a comment below.*

**Comment by JDziewonski98** [comment]
create account page is done, should be able to reuse that code and add on creating schedule

**Comment by sandyl289** [comment]
I just noticed that we already have an issue for this (https://github.com/McGill-ECSE321-Winter2021/project-group-09/issues/178)
I'll close this issue
