### ISSUE TITLE
Appointment tab: Book Appointment (Customer)

### ISSUE THREAD

**Issue by sandyl289** [McGill-ECSE321-Winter2021/project-group-09#163]
### **🏁 Setup**
- [x] **Assign** yourself to this issue 

### **✅ To do:**
- [x] Read [Detailed Use Case: Book Appointment](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Detailed-Use-Cases#use-case-book-appointment)
- [x] **Draw** page mockup using [Whimsical](https://whimsical.com/repairshop-6v7GHoRVFfSSvyvUdeHaQ8) 
(After clicking on the link, you must sign in with your Google Account)

**Frontend**
- [x] Implement layout
- [x] Make it use data from database
- [x] Modify it so that it uses the logged-in user's token
- [x] Change timestamp formats to local time
- [x] Add bad request responses

### **🆘 If you need help for the issue you’re working on:**

**1) Write** comments in this issue 
**2) Add** label ![image](https://user-images.githubusercontent.com/70775435/112154839-0b51fd80-8bbb-11eb-82ae-9f47dab449b0.png)
**3) Copy** the issue link and **paste** it to Discord's `#🐛issues` channel
**4)** When solved, **strike** the message in `#🐛issues`, **mark it** as `(SOLVED)`  + **remove** label `help wanted` + **write** comments in this issue 

### *Whenever something is done write a comment below.*

**Comment by T-Syme** [comment]
Waiting for [Setup Frontend](https://github.com/McGill-ECSE321-Winter2021/project-group-09/pull/155) to be merged before starting the code...

**Comment by T-Syme** [comment]
Initial version is done, but is using static data

**Comment by T-Syme** [comment]
This is nearly done now (appointments can be booked)
Still need to change timestamps to local times and provide better error messages for 400 responses

**Comment by T-Syme** [comment]
This has been completed
