### ISSUE TITLE
Business tab: View & Delete Holidays (Admin)

### ISSUE THREAD

**Issue by sandyl289** [McGill-ECSE321-Winter2021/project-group-09#168]
### **🏁 Setup**
- [x] **Assign** yourself to this issue 

### **✅ To do:**
- [x] **Draw** page mockup using [Whimsical](https://whimsical.com/repairshop-6v7GHoRVFfSSvyvUdeHaQ8) 
(After clicking on the link, you must sign in with your Google Account)

**Frontend**
- [x] View all holidays
- [x] Select a holiday
- [x] Delete it
- [x] If there are no holidays: display no holidays (if have time)
- [x] Implement frontend

### **🆘 If you need help for the issue you’re working on:**

**1) Write** comments in this issue 
**2) Add** label ![image](https://user-images.githubusercontent.com/70775435/112154839-0b51fd80-8bbb-11eb-82ae-9f47dab449b0.png)
**3) Copy** the issue link and **paste** it to Discord's `#🐛issues` channel
**4)** When solved, **strike** the message in `#🐛issues`, **mark it** as `(SOLVED)`  + **remove** label `help wanted` + **write** comments in this issue 

### *Whenever something is done write a comment below.*

**Comment by sandyl289** [comment]
# UI Mockup  done!

# PLAN A (to make it similar to Jacek's view & cancel appointment)
![image](https://user-images.githubusercontent.com/70775435/112766371-7ba7b700-8fdf-11eb-92f7-fe894f33e827.png)

# PLAN B
![image](https://user-images.githubusercontent.com/70775435/112697417-da452780-8e5d-11eb-8b4e-cb6223962241.png)

# PLAN C
![image](https://user-images.githubusercontent.com/70775435/112697437-e4ffbc80-8e5d-11eb-93ec-c87ac4bea0fc.png)

**Comment by sandyl289** [comment]
~It seems like the holidays are not being properly deleted from the list of holidays~ **(SOLVED)**

**Comment by sandyl289** [comment]
**Fixed** delete holidays (Commit: 646d7bb2a53dcaf2ff2613110a1573b82194c873)
- The selected holiday wasn't being properly deleted from the business (list of holidays)  (BusinessRepository)
- The selected holiday should now be deleted from both BusinessRepository and TimeslotRepository
- Added exception if business not found just like `add holiday`
- All tests pass (Repository & Service)

# Tested on Postman:

## Add Holiday
![image](https://user-images.githubusercontent.com/70775435/112764159-501fcf00-8fd5-11eb-8b18-0b264c5e7e55.png)

## Get Business Info
![image](https://user-images.githubusercontent.com/70775435/112764189-6c237080-8fd5-11eb-8a25-4c2a5b2917c4.png)

## Delete Holiday
![image](https://user-images.githubusercontent.com/70775435/112764212-82313100-8fd5-11eb-96df-37eb12356917.png)

## Get Business Info
![image](https://user-images.githubusercontent.com/70775435/112764227-8fe6b680-8fd5-11eb-807f-bf3d60e5765c.png)

**Comment by sandyl289** [comment]
I'm still alive... _debugging_

**Comment by sandyl289** [comment]
I might be missing some components from main. I'll commit an initial version (broken code) to be able to pull from main
Commit: 3daa04c7a0fe1fdc1e97bc00677dd4ed48575887

*Resolving*  merge conflicts

**Comment by sandyl289** [comment]
*trying to fix the errors* 
![image](https://user-images.githubusercontent.com/70775435/112768832-e828b300-8feb-11eb-80bd-b8fd07b038cc.png)

![image](https://user-images.githubusercontent.com/70775435/112769175-a3058080-8fed-11eb-9f13-da604f71473f.png)

**Comment by sandyl289** [comment]
- **Fixed(?)** error `cannot read property data of undefined` (Don't know why it didn't work and why it does now

# What will be displayed if there are no holidays:
![image](https://user-images.githubusercontent.com/70775435/112770151-4c9b4080-8ff3-11eb-9ab7-2b060bc904cb.png)

**Comment by sandyl289** [comment]
More errors + problem with displaying holidays
![image](https://user-images.githubusercontent.com/70775435/112770483-da2b6000-8ff4-11eb-9a10-57da34ca3b89.png)

![image](https://user-images.githubusercontent.com/70775435/112770353-6a1cda00-8ff4-11eb-8f4a-ff75d5ba099e.png)

**Comment by sandyl289** [comment]
*still debugging*

At least the delete buttons showed up! 
![image](https://user-images.githubusercontent.com/70775435/112774247-0ea81780-9007-11eb-9198-5c7adfa12227.png)

# Errors are back 😢
![image](https://user-images.githubusercontent.com/70775435/112774388-84ac7e80-9007-11eb-91f4-389fd28eedcf.png)

**Comment by JDziewonski98** [comment]
You are getting those errors because the error is happening in the .then() block of the axios call. That's why you should handle your e.response queries with a if '(e.response){}' (see the login page), since e.response will only exist if its a BACKEND error. So it looks like some item in the holidays.foreach is undefined, not sure why, I would put a console.log(holidays) before the foreach loop to see the form of the array when the error happens. Maybe you already realized all that

**Comment by sandyl289** [comment]
*trying* to make the successful delete message appear +  put event `event.preventDefault()`

**Comment by sandyl289** [comment]
# Successful message when delete a holiday:
![image](https://user-images.githubusercontent.com/70775435/112844222-7bf09280-9071-11eb-8ea9-df199e852e10.png)

**Comment by sandyl289** [comment]
It seems like we don't need `event.preventDefault()` if we don't have a `<b-form @submit="onSubmit">`
