### ISSUE TITLE
Service tab: View Services (everyone)

### ISSUE THREAD

**Issue by sandyl289** [McGill-ECSE321-Winter2021/project-group-09#170]
### **🏁 Setup**
- [x] **Assign** yourself to this issue 

### **✅ To do:**
- [x] **Draw** page mockup using [Whimsical](https://whimsical.com/repairshop-6v7GHoRVFfSSvyvUdeHaQ8) 
(After clicking on the link, you must sign in with your Google Account)

**Frontend**

- [x] Display all services 
- [x] If no services, display no service
- [x] Implement frontend

### **🆘 If you need help for the issue you’re working on:**

**1) Write** comments in this issue 
**2) Add** label ![image](https://user-images.githubusercontent.com/70775435/112154839-0b51fd80-8bbb-11eb-82ae-9f47dab449b0.png)
**3) Copy** the issue link and **paste** it to Discord's `#🐛issues` channel
**4)** When solved, **strike** the message in `#🐛issues`, **mark it** as `(SOLVED)`  + **remove** label `help wanted` + **write** comments in this issue 

### *Whenever something is done write a comment below.*

**Comment by sandyl289** [comment]
### If no service:
![image](https://user-images.githubusercontent.com/70775435/112472388-72022300-8d43-11eb-803a-673ca5d5bc1c.png)


### What I have for now (Static)
![image](https://user-images.githubusercontent.com/70775435/112473025-387de780-8d44-11eb-81b1-a193385aee89.png)



-  For the time being, I put the "View Services" on Jacek's navbar. When everything is done, we might  put the "Add Service" & "View Service" into "Service" tab?
- I'm trying to figure out how to add things dynamically into the table

**Comment by sandyl289** [comment]
# View All Services (I was able to add duplicate services by adding a space at the end of the service name) We'll just have to make sure not to put an extra space for the demo
![image](https://user-images.githubusercontent.com/70775435/112543208-d21cb780-8d8b-11eb-8594-5fc3f3b0de78.png)

**Comment by T-Syme** [comment]
I'd suggest trimming the whitespace from the service name before checking if it exists. This can be done with `serviceName.trim()`
(https://www.w3schools.com/jsref/jsref_trim_string.asp)

**Comment by sandyl289** [comment]
# It has been fixed! (Thanks Tyler! )
## Add New Service
![image](https://user-images.githubusercontent.com/70775435/112545540-b666e080-8d8e-11eb-84bd-fbff3d12846a.png)

## Successful Message
![image](https://user-images.githubusercontent.com/70775435/112545582-c252a280-8d8e-11eb-8c0f-1dd595e6a74a.png)

## If service name already exists
![image](https://user-images.githubusercontent.com/70775435/112545686-e44c2500-8d8e-11eb-8cc3-f2bc8ca74bd1.png)
