### ISSUE TITLE
Technician tab: Modify/Delete technician's schedule (Admin)

### ISSUE THREAD

**Issue by sandyl289** [McGill-ECSE321-Winter2021/project-group-09#175]
### **🏁 Setup**
- [x] **Assign** yourself to this issue 
- [x] Read [Detailed Use Case modify technician work hours](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Detailed-Use-Cases#use-case-modify-technicians-work-hours)

### **✅ To do:**

- [x] **Draw** page mockup using [Whimsical](https://whimsical.com/repairshop-6v7GHoRVFfSSvyvUdeHaQ8) 
(After clicking on the link, you must sign in with your Google Account)
- [x] Select a technician and delete the entire schedule 
- [x] Select technician, select single workhour and delete selected work hours of a technician
- [x] implement frontend

### **🆘 If you need help for the issue you’re working on:**

**1) Write** comments in this issue 
**2) Add** label ![image](https://user-images.githubusercontent.com/70775435/112154839-0b51fd80-8bbb-11eb-82ae-9f47dab449b0.png)
**3) Copy** the issue link and **paste** it to Discord's `#🐛issues` channel
**4)** When solved, **strike** the message in `#🐛issues`, **mark it** as `(SOLVED)`  + **remove** label `help wanted` + **write** comments in this issue 

### *Whenever something is done write a comment below.*

**Comment by T-Syme** [comment]
From the detailed use case, it sounds like we'll also need a way to add a timeslot for the technician's hours --> might need to be added to the backend

**Comment by T-Syme** [comment]
This is now complete. 

**Tests:**

**Initial data:**

Appointment as seen by technician:
![image](https://user-images.githubusercontent.com/70815823/112904064-66518c00-90b6-11eb-84f0-fe9093f339f9.png)

Appointment as seen by customer:
![image](https://user-images.githubusercontent.com/70815823/112904129-7ec1a680-90b6-11eb-979a-58ebdf3ca621.png)

Work hours of the target technician:
![image](https://user-images.githubusercontent.com/70815823/112904210-98fb8480-90b6-11eb-88bf-0e1cdbafbeb7.png)
(Note the appointment is in the fourth time slot)

**Modification process:**
![image](https://user-images.githubusercontent.com/70815823/112904364-d7913f00-90b6-11eb-9efd-5c3818d7ad36.png)
![image](https://user-images.githubusercontent.com/70815823/112904399-e7a91e80-90b6-11eb-8670-f67f8f376c28.png)
![image](https://user-images.githubusercontent.com/70815823/112904425-f0015980-90b6-11eb-8732-20085c306f43.png)
![image](https://user-images.githubusercontent.com/70815823/112904448-f8599480-90b6-11eb-9169-f163277a1ff4.png)

**Results:**

Appointment as seen by technician:
![image](https://user-images.githubusercontent.com/70815823/112904542-158e6300-90b7-11eb-922e-3f45a72d3144.png)

Appointment as seen by customer:
![image](https://user-images.githubusercontent.com/70815823/112904572-2343e880-90b7-11eb-94fd-136004d06e6f.png)
(Only the other appointment is left)

Work hours of the target technician:
![image](https://user-images.githubusercontent.com/70815823/112904616-33f45e80-90b7-11eb-850c-6e476a8e287e.png)

Using the same process, it also removes the work hours that don't have appointments:
![image](https://user-images.githubusercontent.com/70815823/112904732-5edeb280-90b7-11eb-98c4-3a8960d47729.png)
(Removed the third time slot)

**Comment by T-Syme** [comment]
I just noticed that a few of the service tests are failing. I'm fixing them now 
_(They have been fixed)_
