### ISSUE TITLE
ONLY IF HAVE TIME Frontend Design (Make All Pages Uniform and pretty...)

### ISSUE THREAD

**Issue by sandyl289** [McGill-ECSE321-Winter2021/project-group-09#186]
### **🏁 Setup**
- [x] **Assign** yourself to this issue 

### **✅ To do:**
- [x] same color
- [x] same size
- [x] same background color
- [ ] same icons
- [x] Tabs with dropdown menu

**Comment by T-Syme** [comment]
This has been done over the last couple of days
