### ISSUE TITLE
Mobile Frontend: Welcome & Login

### ISSUE THREAD

**Issue by sandyl289** [McGill-ECSE321-Winter2021/project-group-09#198]
## 📜 Description

- 1st screen when we open the application
- `Login Page` from [our website](https://lit-fortress-63303.herokuapp.com/#/Login):

![image](https://user-images.githubusercontent.com/70775435/113605023-1756aa00-9614-11eb-8c5a-1a2963f86900.png)

## **✅ To do:**
- [ ] Implement mobile frontend 
- [ ] Add link to Register (hyperlink?)

## **🆘 If need help for the issue you’re working on:**

**1) Write** comments in this issue 
**2) Add** label ![image](https://user-images.githubusercontent.com/70775435/112154839-0b51fd80-8bbb-11eb-82ae-9f47dab449b0.png)
**3) Copy** the issue link and **paste** it to Discord's `#🐛issues` channel
**4)** When solved, **strike** the message in `#🐛issues`, **mark it** as `(SOLVED)`  + **remove** label `help wanted` + **write** comments in this issue

**Comment by JDziewonski98** [comment]
login done
