### ISSUE TITLE
Wiki list of 15 functional/non-functional requirements. 

### ISSUE THREAD

**Issue by zhannaklimanova** [McGill-ECSE321-Winter2021/project-group-09#2]
In the Wiki pages, create a list of 15 functional/non-functional requirements with a unique ID that links to the equivalent requirement issue.

**Comment by sandyl289** [comment]
- On February 7, 2021 ([Meeting S1.2](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Sprint-1:-Project-Report#s12---uml-diagramrequirements-)), we selected 10 functional requirements and 3 non-functional requirements.
- On February 10, 2021, ([Meeting S1.3](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Sprint-1:-Project-Report#s13---requirementsuse-casessetups-)), we selected 14 most important requirements.
- On February 11, 2021 ([Meeting S1.4](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Sprint-1:-Project-Report#s14---clarificationrecap-from-oh-)),  we selected the last requirement and finalized all requirements.
- I created a wiki page  called "Project Requirements" and added the 15 requirements to the wiki page. 
We now have 12 functional requirements and 3 non-functional requirements. 
(See [Final 15 requirements](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Project-Requirements))
