### ISSUE TITLE
Mobile Frontend: Book appointment

### ISSUE THREAD

**Issue by sandyl289** [McGill-ECSE321-Winter2021/project-group-09#203]
## 📜 Description

- Allows the customer to book an appointment
- `Book Appointment` Page from [our website](https://lit-fortress-63303.herokuapp.com/#/):

### 1) Select Service
![image](https://user-images.githubusercontent.com/70775435/113608427-94841e00-9618-11eb-9816-7abc524e10c8.png)

### 2) Select Date & Time or Enter Future Date
![image](https://user-images.githubusercontent.com/70775435/113608613-ce552480-9618-11eb-8930-0e152627dcd4.png)
![image](https://user-images.githubusercontent.com/70775435/113608695-e462e500-9618-11eb-9832-96a3f072db58.png)

### 3) Confirm Appointment 
![image](https://user-images.githubusercontent.com/70775435/113608804-0197b380-9619-11eb-919a-c393d78f25fc.png)

### 4) Confirmation
![image](https://user-images.githubusercontent.com/70775435/113608843-0e1c0c00-9619-11eb-8847-cbb31dfa7551.png)

## **✅ To do:**
- [x] Implement mobile frontend 

## **🆘 If need help for the issue you’re working on:**

**1) Write** comments in this issue 
**2) Add** label ![image](https://user-images.githubusercontent.com/70775435/112154839-0b51fd80-8bbb-11eb-82ae-9f47dab449b0.png)
**3) Copy** the issue link and **paste** it to Discord's `#🐛issues` channel
**4)** When solved, **strike** the message in `#🐛issues`, **mark it** as `(SOLVED)`  + **remove** label `help wanted` + **write** comments in this issue

**Comment by T-Syme** [comment]
I'm going to come back to this after creating a basic menu

**Comment by T-Syme** [comment]
Part 1 (displaying and saving the selected service) is done now
![image](https://user-images.githubusercontent.com/70815823/114276482-c5879880-99f4-11eb-8026-1e9e8138c4aa.png)

**Comment by T-Syme** [comment]
Everything should be complete, and seems to be working with the token and email from a logged in user.
I still need to go through all of the cases that result in errors to make sure that they are being displayed properly
**(Done)**

**Comment by T-Syme** [comment]
Complete. See pull request above
