### ISSUE TITLE
(AFTER CODES ARE DONE) "User Documentation" wiki page 

### ISSUE THREAD

**Issue by sandyl289** [McGill-ECSE321-Winter2021/project-group-09#207]
# Instructions

![image](https://user-images.githubusercontent.com/70775435/113952635-09f01a00-97e4-11eb-9db0-d3ab176ebef9.png)

# Example
- See example from [last semester](https://github.com/McGill-ECSE321-Fall2019/project-group-16/wiki/User-Documentation)

# **🏁 Setups**

- [x] **Create** "User Documentation" wiki page
- [x] **Add** hyperlink to sidebar
- [x] **Add** hyperlink to Home Page + Readme.md

# ✅ **TO DO:**
- [x] Write draft on [Google Doc Draft User Documentation](https://docs.google.com/document/d/1zrP2b0E7z5l_MEicGYF6q6pKNg6SgOmdP7r860y_EQA/edit?usp=sharing)
- [x] User documentation for Android to [User Documentation: Android 📜📱](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/User-Documentation:-Android-%F0%9F%93%9C%F0%9F%93%B1)
- [x] User documentation for Website to [User Documentation: Web 📜🕸️](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/User-Documentation:-Web-%F0%9F%93%9C%F0%9F%95%B8%EF%B8%8F)

**Comment by sandyl289** [comment]
Done! 
![image](https://user-images.githubusercontent.com/70775435/113960605-b802c080-97f2-11eb-8182-5bf8d9c03eb9.png)

**Comment by Shaswata79** [comment]
CUSTOMER VIEW

![image](https://user-images.githubusercontent.com/57040344/114432608-b36b4d00-9be2-11eb-96be-364359c01366.png)
![image](https://user-images.githubusercontent.com/57040344/114432792-e0b7fb00-9be2-11eb-991d-ecace30749d6.png)
![image](https://user-images.githubusercontent.com/57040344/114433396-97b47680-9be3-11eb-94ba-d5393f33193d.png)
![image](https://user-images.githubusercontent.com/57040344/114434353-ba935a80-9be4-11eb-9b25-00e4984bf9d1.png)
![image](https://user-images.githubusercontent.com/57040344/114434773-3392b200-9be5-11eb-89c3-62c428b0fc77.png)
![image](https://user-images.githubusercontent.com/57040344/114435321-da774e00-9be5-11eb-9301-53917e67069a.png)
![image](https://user-images.githubusercontent.com/57040344/114436605-5920bb00-9be7-11eb-9f66-88c1b4f147b4.png)
![image](https://user-images.githubusercontent.com/57040344/114436931-be74ac00-9be7-11eb-955e-dbd3b32131a4.png)

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 00 54 55" src="https://user-images.githubusercontent.com/59708333/114816019-59ef5380-9d85-11eb-9d9e-f37b739c5c03.png">

**Comment by zhannaklimanova** [comment]
<img width="1438" alt="Screen Shot 2021-04-15 at 00 57 30" src="https://user-images.githubusercontent.com/59708333/114816167-9c189500-9d85-11eb-87c2-f6cd9e79a05a.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 00 59 32" src="https://user-images.githubusercontent.com/59708333/114816312-e1d55d80-9d85-11eb-9b76-12b0b3a29438.png">

**Comment by zhannaklimanova** [comment]
TECHNICIAN VIEW

<img width="1440" alt="Screen Shot 2021-04-15 at 01 04 04" src="https://user-images.githubusercontent.com/59708333/114816635-85267280-9d86-11eb-9c75-17ec3e005398.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 07 27" src="https://user-images.githubusercontent.com/59708333/114816873-04b44180-9d87-11eb-95fa-b1c84865f0a9.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 10 10" src="https://user-images.githubusercontent.com/59708333/114817074-5d83da00-9d87-11eb-9d9d-9a50949cb446.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 12 43" src="https://user-images.githubusercontent.com/59708333/114817290-b5badc00-9d87-11eb-859e-bbd939fdd9a3.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 15 37" src="https://user-images.githubusercontent.com/59708333/114817522-2661f880-9d88-11eb-9a3b-2fb8df0b3d01.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 17 26" src="https://user-images.githubusercontent.com/59708333/114817633-5e693b80-9d88-11eb-9c0b-326d10e842c3.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 20 17" src="https://user-images.githubusercontent.com/59708333/114817879-c750b380-9d88-11eb-8fab-8464c61fb600.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 21 31" src="https://user-images.githubusercontent.com/59708333/114818074-1e568880-9d89-11eb-99bf-f7eb17c58711.png">

**Comment by zhannaklimanova** [comment]
ADMIN VIEW

<img width="1440" alt="Screen Shot 2021-04-15 at 01 25 43" src="https://user-images.githubusercontent.com/59708333/114818345-a63c9280-9d89-11eb-93dd-7ab5cd938546.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 29 09" src="https://user-images.githubusercontent.com/59708333/114818578-016e8500-9d8a-11eb-989d-62acce30dfe8.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 30 39" src="https://user-images.githubusercontent.com/59708333/114818722-40043f80-9d8a-11eb-877a-ff34cdc046d8.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 31 41" src="https://user-images.githubusercontent.com/59708333/114818779-5d390e00-9d8a-11eb-9ce8-b970a9d80282.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 35 45" src="https://user-images.githubusercontent.com/59708333/114819109-ee0fe980-9d8a-11eb-83f3-b6058ec64a0c.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 36 46" src="https://user-images.githubusercontent.com/59708333/114819200-15ff4d00-9d8b-11eb-8ece-57bc4d7cee3b.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 43 12" src="https://user-images.githubusercontent.com/59708333/114819794-ffa5c100-9d8b-11eb-9814-d56e278e5219.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 48 23" src="https://user-images.githubusercontent.com/59708333/114820230-b013c500-9d8c-11eb-9360-31b1225c4877.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 56 00" src="https://user-images.githubusercontent.com/59708333/114820906-c1a99c80-9d8d-11eb-85d6-cab2f961103f.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 01 59 45" src="https://user-images.githubusercontent.com/59708333/114821270-4c8a9700-9d8e-11eb-989c-b128f3734020.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 02 03 36" src="https://user-images.githubusercontent.com/59708333/114821650-e0f4f980-9d8e-11eb-9aaa-ad4b3770b166.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 02 05 09" src="https://user-images.githubusercontent.com/59708333/114821759-0a158a00-9d8f-11eb-83cc-3be806af204e.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 02 06 21" src="https://user-images.githubusercontent.com/59708333/114821854-33ceb100-9d8f-11eb-8975-d4eeeefd4c54.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 02 06 54" src="https://user-images.githubusercontent.com/59708333/114821911-4a750800-9d8f-11eb-8519-0c29a8c00861.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 02 07 46" src="https://user-images.githubusercontent.com/59708333/114822007-6d9fb780-9d8f-11eb-9002-42c5057ffdb9.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 02 09 06" src="https://user-images.githubusercontent.com/59708333/114822117-9922a200-9d8f-11eb-9a8a-31e3a004ab54.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 02 10 40" src="https://user-images.githubusercontent.com/59708333/114822278-cec78b00-9d8f-11eb-9ea6-2394bc920e9c.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 02 11 47" src="https://user-images.githubusercontent.com/59708333/114822386-f880b200-9d8f-11eb-9f1f-a51b7957fc6d.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 02 12 20" src="https://user-images.githubusercontent.com/59708333/114822441-0fbf9f80-9d90-11eb-9214-daeccbad50bc.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 02 12 54" src="https://user-images.githubusercontent.com/59708333/114822542-3978c680-9d90-11eb-8486-6e93daaec44d.png">

**Comment by zhannaklimanova** [comment]
<img width="1440" alt="Screen Shot 2021-04-15 at 02 14 17" src="https://user-images.githubusercontent.com/59708333/114822624-5ad9b280-9d90-11eb-9c46-3942970c0b5a.png">

**Comment by sandyl289** [comment]
![image](https://user-images.githubusercontent.com/70775435/114966805-528d8000-9e41-11eb-906e-40bb30499110.png)
![image](https://user-images.githubusercontent.com/70775435/114966856-6afd9a80-9e41-11eb-8761-f4bf9b8e5ae3.png)
![image](https://user-images.githubusercontent.com/70775435/114966915-849ee200-9e41-11eb-97c9-478af16b22cf.png)

**Comment by sandyl289** [comment]
![image](https://user-images.githubusercontent.com/70775435/114967540-a51b6c00-9e42-11eb-9988-91f59ef7fef0.png)

**Comment by sandyl289** [comment]
![image](https://user-images.githubusercontent.com/70775435/114968286-0abc2800-9e44-11eb-9c25-5b1d361aab73.png)
![image](https://user-images.githubusercontent.com/70775435/114968323-1871ad80-9e44-11eb-8423-c0090eac1aec.png)

**Comment by sandyl289** [comment]
![image](https://user-images.githubusercontent.com/70775435/114969339-2e806d80-9e46-11eb-9982-58fe40e19ddf.png)
![image](https://user-images.githubusercontent.com/70775435/114969397-4821b500-9e46-11eb-9941-96048fd99eee.png)

**Comment by sandyl289** [comment]
![image](https://user-images.githubusercontent.com/70775435/114970066-abf8ad80-9e47-11eb-904b-625f33ca4a80.png)
![image](https://user-images.githubusercontent.com/70775435/114970098-bc108d00-9e47-11eb-874f-1f1f050b2acd.png)

**Comment by sandyl289** [comment]
![image](https://user-images.githubusercontent.com/70775435/114971800-20811b80-9e4b-11eb-961c-dba97d7a77c2.png)
![image](https://user-images.githubusercontent.com/70775435/114971845-342c8200-9e4b-11eb-9ecf-aa4dd63edab8.png)
![image](https://user-images.githubusercontent.com/70775435/114971883-47d7e880-9e4b-11eb-930e-e7701ad774a9.png)
![image](https://user-images.githubusercontent.com/70775435/114971896-51615080-9e4b-11eb-9ace-c5cbe17773f5.png)
![image](https://user-images.githubusercontent.com/70775435/114971938-69d16b00-9e4b-11eb-98e3-2902bba58dc2.png)
![image](https://user-images.githubusercontent.com/70775435/114971960-71910f80-9e4b-11eb-9ac5-c17682b1836c.png)

**Comment by sandyl289** [comment]
# Add work hours tab
![image](https://user-images.githubusercontent.com/70775435/115032516-6368e080-9e97-11eb-8909-89ed8479a7d8.png)

# Select corresponding technician's email
![image](https://user-images.githubusercontent.com/70775435/115032584-78457400-9e97-11eb-9f56-ad2b598d0d60.png)

# Choose  weekday and enter start time and end time in format HH:MM
![image](https://user-images.githubusercontent.com/70775435/115032841-c490b400-9e97-11eb-8fc6-7e7cd23f926a.png)

# Confirm
![image](https://user-images.githubusercontent.com/70775435/115033040-f570e900-9e97-11eb-930c-d724aefd6e36.png)

# Successful message
![image](https://user-images.githubusercontent.com/70775435/115033126-0f123080-9e98-11eb-9c99-2857fae1be2f.png)

**Comment by sandyl289** [comment]
# Select Delete Work Hours tab
![image](https://user-images.githubusercontent.com/70775435/115033272-3bc64800-9e98-11eb-8d22-55285b2b0f9b.png)

# Select corresponding technician's email
![image](https://user-images.githubusercontent.com/70775435/115033352-54cef900-9e98-11eb-9d8f-9d6d4f056787.png)

# Select work hours to remove
![image](https://user-images.githubusercontent.com/70775435/115033444-74feb800-9e98-11eb-9663-29178d6da661.png)

# Confirm 
![image](https://user-images.githubusercontent.com/70775435/115033499-80ea7a00-9e98-11eb-9ac6-9ce405472bb0.png)

# Successful  message
![image](https://user-images.githubusercontent.com/70775435/115033538-8b0c7880-9e98-11eb-8e83-2cbf8015c1e2.png)

**Comment by sandyl289** [comment]
- User documentation for Website to [User Documentation: Web 📜🕸️](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/User-Documentation:-Web-%F0%9F%93%9C%F0%9F%95%B8%EF%B8%8F) is done
- Added Table of Contents

**Comment by sandyl289** [comment]
# Contact Us
![image](https://user-images.githubusercontent.com/70775435/115071381-3121a800-9ec4-11eb-9206-05a6f5f5e952.png)

**Comment by sandyl289** [comment]
# View Services
![image](https://user-images.githubusercontent.com/70775435/115071454-472f6880-9ec4-11eb-853f-8e45c1c64da9.png)

**Comment by sandyl289** [comment]
# Register
![image](https://user-images.githubusercontent.com/70775435/115072468-a477e980-9ec5-11eb-97fb-10b81cc3a14a.png)

**Comment by sandyl289** [comment]
# Login
![image](https://user-images.githubusercontent.com/70775435/115072630-cffad400-9ec5-11eb-9072-59efbfb41302.png)

**Comment by sandyl289** [comment]
# Log Out
![image](https://user-images.githubusercontent.com/70775435/115073127-ef91fc80-9ec5-11eb-8cb6-0117a9d8306c.png)

**Comment by sandyl289** [comment]
# Book Appointment

![image](https://user-images.githubusercontent.com/70775435/115073266-151f0600-9ec6-11eb-8346-633617b0ecc1.png)
![image](https://user-images.githubusercontent.com/70775435/115073589-8bbc0380-9ec6-11eb-91eb-4b11ee504831.png)
![image](https://user-images.githubusercontent.com/70775435/115073630-9bd3e300-9ec6-11eb-81c6-2723a0bae90d.png)

# Home Page
![image](https://user-images.githubusercontent.com/70775435/115073655-a55d4b00-9ec6-11eb-9379-2cf6e60316e7.png)

**Comment by sandyl289** [comment]
# View Appointments
![image](https://user-images.githubusercontent.com/70775435/115073693-b312d080-9ec6-11eb-8ad4-5effd2b0af53.png)

# Cancel Appointment
![image](https://user-images.githubusercontent.com/70775435/115073735-befe9280-9ec6-11eb-832e-0166254e16d3.png)

**Comment by sandyl289** [comment]
# Press login
![image](https://user-images.githubusercontent.com/70775435/115075040-7cd65080-9ec8-11eb-96c5-dc0773df59f3.png)

**Comment by sandyl289** [comment]
# Press Contact Us
![image](https://user-images.githubusercontent.com/70775435/115075173-ac855880-9ec8-11eb-848f-2d311625f9dd.png)

# Press View Services
![image](https://user-images.githubusercontent.com/70775435/115075208-b909b100-9ec8-11eb-8d82-20bc63583a4b.png)

# Press Register
![image](https://user-images.githubusercontent.com/70775435/115075246-cd4dae00-9ec8-11eb-8a7f-9239b3a978df.png)

# Press Login
![image](https://user-images.githubusercontent.com/70775435/115075281-d8084300-9ec8-11eb-90be-068dce6ab2e2.png)

**Comment by sandyl289** [comment]
# AFTER LOGGING IN

# Press Book Appointment
![image](https://user-images.githubusercontent.com/70775435/115075450-1867c100-9ec9-11eb-85b3-3beec322197a.png)

# Press View Appointments
![image](https://user-images.githubusercontent.com/70775435/115075502-29b0cd80-9ec9-11eb-8d50-14ec026ed34d.png)

# Press Cancel Appointment
![image](https://user-images.githubusercontent.com/70775435/115075535-37665300-9ec9-11eb-8579-9640d37c47cb.png)

**Comment by sandyl289** [comment]
Done!
