### ISSUE TITLE
5 use case specifications.

### ISSUE THREAD

**Issue by zhannaklimanova** [McGill-ECSE321-Winter2021/project-group-09#4]
In the Wiki pages, create 5 detailed use case specifications.

**Comment by sandyl289** [comment]
I updated the "Book Appointment"'s detailed use case.
(See [Use Case: Book Appointment](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Detailed-Use-Cases#use-case-book-appointment))

**Comment by T-Syme** [comment]
The detailed use case for "[Cancel Appointment](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Detailed-Use-Cases#use-case-cancel-appointment)" was also updated

**Comment by sandyl289** [comment]
The detailed use case for "[Use Case: Create New Employee Account Along With a Schedule](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Detailed-Use-Cases#use-case-create-new-employee-account-along-with-a-schedule)" was updated.

**Comment by sandyl289** [comment]
- The detailed use case for "[Register](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Detailed-Use-Cases#use-case-register)" was updated by Shaswata.
- The detailed use case for "[Modify Technician’s Work Hours](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Detailed-Use-Cases#use-case-modify-technicians-work-hours)" was updated by Zhanna.

**Comment by sandyl289** [comment]
All detailed use cases have been updated on the wiki  (See [Detailed Use Cases](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Detailed-Use-Cases))
