### ISSUE TITLE
Use case diagram.

### ISSUE THREAD

**Issue by zhannaklimanova** [McGill-ECSE321-Winter2021/project-group-09#5]
Create use case diagram in the Wiki pages.

**Comment by sandyl289** [comment]
I created 3 use case diagrams See [Use Case Diagram](https://drive.google.com/file/d/1tHlgwTNbxNx1W7NiybqA6-m-mCSKd8HD/view?usp=sharing)

- Image for Use Case Diagram: Registration and Login: ![image](https://user-images.githubusercontent.com/70775435/108015877-3acf8200-6fdf-11eb-8718-42fa0f6b56cf.png)

- Image for Use Case Diagram: Appointments ![image](https://user-images.githubusercontent.com/70775435/108015944-5d619b00-6fdf-11eb-8628-c9914424da96.png)

- Image for Use Case Diagram: Business 
![image](https://user-images.githubusercontent.com/70775435/108016013-897d1c00-6fdf-11eb-9d5f-eb5e08029586.png)

**Comment by sandyl289** [comment]
I added the use case diagrams on the wiki [Use Case Diagram wiki page](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Use-Case-Diagram)

**Comment by sandyl289** [comment]
We'll need to verify the use case diagrams before we submit. 
[Link to Use Case Diagram wiki page](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Use-Case-Diagram)
[draw.io : Original Use Case Diagrams](https://drive.google.com/file/d/1tHlgwTNbxNx1W7NiybqA6-m-mCSKd8HD/view?usp=sharing)

**Comment by sandyl289** [comment]
All use case diagrams are on the wiki page now. (See [Use Case Diagrams](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Use-Case-Diagram))
