### ISSUE TITLE
"Sprint 2 : Project Report " wiki page

### ISSUE THREAD

**Issue by sandyl289** [McGill-ECSE321-Winter2021/project-group-09#58]
- [x]  Create the wiki page + skeleton
- [x] Add page to sidebar + hyperlink
- [x] Add hyperlink to the home page
- [x] Add meeting notes (including key design decisions taken by team)
- [x] Add hyperlink to each meeting note

**Everyone: (Before the deadline)**
- [x] Update contributions part in effort table
- [x] Update effort hours in contribution part

**Comment by sandyl289** [comment]
**Update on things done:**
- I created the "[Sprint 2: Project Report](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Sprint-2:-Project-Report)" wiki page + skeleton 
- I added a hyperlink to the "Sprint 2: Project Report" and "Sprint 2: Meeting notes" on the homepage</br> (See [Home page, section Sprint 2](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki#sprint-2-%EF%B8%8F))
- I added the page in the the sidebar (with hyperlink) 
- I added the meeting note "[S2.1 - Retrospective/Planning 🤝](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Sprint-2:-Project-Report#s21---retrospectiveplanning-)"
- I added a hyperlink to the meeting note "S2.1 - Retrospective/Planning 🤝" in the table of contents of the "Sprint 2: Project Report (See links under [Sprint 2: Meeting Notes 📝](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Sprint-2:-Project-Report#sprint-2-meeting-notes-))

**Comment by T-Syme** [comment]
- I added [meeting notes for S2.4](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Sprint-2:-Project-Report#s24-check-in)

**Comment by sandyl289** [comment]
Done!
