### ISSUE TITLE
Update the domain model

### ISSUE THREAD

**Issue by JDziewonski98** [McGill-ECSE321-Winter2021/project-group-09#71]

**Comment by sandyl289** [comment]
TODO: Update Domain Model on the [Domain Model](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Domain-Model) page to be similar to the [umple diagram](https://cruise.umple.org/umpleonline/umple.php?model=21020317ygmsb729lf9)
- [ ]  Change the **vacations** to **holidays**
- [ ] Update the associations between Technician, Appointment and TimeSlot
