### ISSUE TITLE
Add Timeslot Holiday (Admin)

### ISSUE THREAD

**Issue by T-Syme** [McGill-ECSE321-Winter2021/project-group-09#77]
Add functionality for adding holidays to the business

**Comment by sandyl289** [comment]
- It has been implemented, but if we want to add the authentication part, we might need to add some lines 

What we have now:

https://github.com/McGill-ECSE321-Winter2021/project-group-09/blob/cc39328d093cf4c6bbffd9433ba147e64df741e2/RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/BusinessService.java#L164-L192

https://github.com/McGill-ECSE321-Winter2021/project-group-09/blob/cc39328d093cf4c6bbffd9433ba147e64df741e2/RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/controller/BusinessController.java#L107-L121
