### ISSUE TITLE
Delete Timeslot Holiday (Admin)

### ISSUE THREAD

**Issue by T-Syme** [McGill-ECSE321-Winter2021/project-group-09#78]
Add functionality for deleting holidays to the business

**Comment by zhannaklimanova** [comment]
This issue can be closed,  I implemented it and tested it in https://github.com/McGill-ECSE321-Winter2021/project-group-09/blob/main/RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/BusinessService.java. The service method is called deleteHoliday and it takes in two time stamps.
